// config.js - generated by GitHub Actions
// It defines global constants used by the pages. Values are filled in
// from GitHub secrets at build time.

const SHEET_ID = '__SHEET_ID__';
// URL to the Google Apps Script web app handling purchases
const PURCHASE_ENDPOINT = '__PURCHASE_ENDPOINT__';
// ID of the Google Apps Script project (separate from web‑app URL)
const ID_SCRIPT = '__ID_SCRIPT__';
